#!/usr/bin/env python

import os

BASE_DIR = os.path.dirname(__file__)

for root, dirs, filenames in os.walk(BASE_DIR):
    if root == BASE_DIR:
        if '.git' in dirs:
            dirs.remove('.git')
    else:
        for filename in filenames:
            path = os.path.join(root, filename)
            relpath = os.path.relpath(path, BASE_DIR)
            split = relpath.split('/')
            package = split[0]
            for i in range(2, len(split) + 1):
                git_path = os.path.join(BASE_DIR, *split[:i])
                home_path = os.path.join(
                    os.environ['HOME'],
                    '.{}'.format(split[1]),
                    *split[2:i]
                )
                print(package, os.path.join(*split), home_path)
                if os.path.isfile(git_path):
                    try:
                        os.symlink(os.path.abspath(path), home_path)
                    except FileExistsError:
                        pass
                    if not os.path.islink(home_path):
                        m = '{} is not a symlink'.format(home_path)
                        raise Exception(m)
                elif os.path.isdir(git_path):
                    try:
                        os.mkdir(home_path)
                    except FileExistsError:
                        pass
                    if not os.path.isdir(home_path):
                        m = '{} is not a directory'.format(home_path)
                        raise Exception(m)
