ZSH=/usr/share/oh-my-zsh
ZSH_THEME="lukerandall"
DISABLE_AUTO_UPDATE="true"

ZSH_TMUX_AUTOSTART="true"

plugins=(archlinux git tmux)
source $ZSH/oh-my-zsh.sh

export EDITOR="emacsclient -t"
export PATH="~/bin:${PATH}"

envoy -t gpg-agent
source <(envoy -p)
